version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose the app on port 8080
    volumes:
      - .:/var/www/html # Mount the project directory
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.5
    container_name: mariadb-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Allow root without a password
      MYSQL_DATABASE: retail
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
